# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Solera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Solera
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  
  target 'SoleraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
